FROM awseward/gh-action-fake5:latest as builder
ENV PATH="/root/.dotnet/tools:${PATH}"
RUN mkdir /build
COPY . /build
WORKDIR /build
RUN dotnet restore
RUN fake build -t bundle:web

FROM mcr.microsoft.com/dotnet/aspnet:2.1-alpine
COPY --from=builder /build/deploy /
WORKDIR /WhatDid
CMD ["dotnet", "WhatDid.dll"]
